"""hydra-py — Python client for the Hydra living database.

Quickstart:

    import asyncio
    from hydra import Hydra, ClaimSubject, ClaimObject

    async def main():
        async with Hydra("http://localhost:8080",
                         token="<bearer>",
                         tenant="tenant_default") as hy:
            resp = await hy.ingest_signal(
                name="cloudtrail/CreateBucket",
                source="node_aws_acct",
            )
            print(resp.event_ids)

            resp = await hy.propose_claim(
                claim_id="claim_anom_001",
                subject=ClaimSubject.dataset("revenue_daily"),
                predicate="is_stale",
                object=ClaimObject.value(True),
                created_by="actor_agent",
                kind="AnomalyFinding",
                confidence=0.91,
            )

    asyncio.run(main())

Public surface in Patch 2:
  - `Hydra` — the async client
  - Wire types: `Node`, `Edge`, `Event`, `Claim`, `Evidence`,
    `Action`, `Outcome`, `IngestResponse`
  - Tagged-union helpers: `ClaimSubject`, `ClaimObject`,
    `EvidenceSource`, `ActionTarget`
  - Type aliases: `EventId`, `NodeId`, etc.
  - Literal enums: `ClaimStatus`, `ClaimKind`, `ActionStatus`,
    `OutcomeKind`
  - Exception hierarchy: `HydraError` + 7 typed subclasses

See HYDRA_SDK_DESIGN_RULES.md at the repo root for the immutable
design rules every patch follows.
"""

__version__ = "0.1.0"

from ._types import (
    Action,
    ActionId,
    ActionPayloadSchema,
    ActionStatus,
    ActionTarget,
    ActorId,
    Anomaly,
    AnomalyEntry,
    AnomalyResponse,
    ApprovalId,
    CascadeId,
    Claim,
    ClaimId,
    ClaimKind,
    ClaimObject,
    ClaimPredicateSchema,
    ClaimStatus,
    ClaimSubject,
    CommitId,
    Confidence,
    CounterfactualDiagnosticsResponse,
    CoverageDiagnosticsResponse,
    CoverageGap,
    CoverageReport,
    DriftDirection,
    Edge,
    EdgeDiff,
    EdgeId,
    EdgeMeta,
    EdgeTypeSchema,
    EntityTypeSchema,
    Event,
    EventId,
    Evidence,
    EvidenceId,
    EvidencePayload,
    EvidencePayloadSchema,
    EvidenceSource,
    EvolutionDiagnosticsResponse,
    EvolutionMetricEntry,
    FieldSchema,
    FireRecord,
    GraphDiff,
    IngestResponse,
    LastPromotionInfo,
    LineageAction,
    LineageApprovalRequest,
    LineageClaim,
    LineageEventSummary,
    LineageEvidence,
    LineageOutcome,
    LineagePolicyDecision,
    LineageResponse,
    MissRecord,
    Node,
    NodeDiff,
    NodeId,
    NodeMeta,
    Outcome,
    OutcomeId,
    OutcomeKind,
    PolicyConditionSchema,
    PolicyDecisionId,
    PolicyId,
    PropertyDiff,
    ReplicaId,
    ReplicationLag,
    ReplicationLagResponse,
    ReplicationMode,
    ReplicationOffset,
    ReplicationPeer,
    ReplicationPeerStatus,
    ReplicationPromotionStatusResponse,
    ReplicationRole,
    ReplicationRoleGetResponse,
    ReplicationStatusResponse,
    RuntimeRole,
    SchemaId,
    SchemaIdResponse,
    SchemaStatus,
    SchemaValidationErrorResponse,
    SnapshotId,
    SubscriptionId,
    SubscriptionOutcome,
    TenantId,
    TypeId,
    ValidationResponse,
    ValueType,
    ValueTypeOf,
)
from .client import Hydra
from .errors import (
    HydraAuthError,
    HydraConnectionError,
    HydraError,
    HydraNotFoundError,
    HydraRateLimitedError,
    HydraReadOnlyFollowerError,
    HydraServerError,
    HydraValidationError,
)

__all__ = [
    "__version__",
    # Client
    "Hydra",
    # Wire types
    "Action",
    "Claim",
    "Edge",
    "EdgeMeta",
    "Event",
    "Evidence",
    "EvidencePayload",
    "IngestResponse",
    "Node",
    "NodeMeta",
    "Outcome",
    # Lineage (Patch 3)
    "LineageAction",
    "LineageApprovalRequest",
    "LineageClaim",
    "LineageEventSummary",
    "LineageEvidence",
    "LineageOutcome",
    "LineagePolicyDecision",
    "LineageResponse",
    # Diagnostics (Patch 3)
    "Anomaly",
    "AnomalyEntry",
    "AnomalyResponse",
    "CounterfactualDiagnosticsResponse",
    "CoverageDiagnosticsResponse",
    "CoverageGap",
    "CoverageReport",
    "EdgeDiff",
    "EvolutionDiagnosticsResponse",
    "EvolutionMetricEntry",
    "FireRecord",
    "GraphDiff",
    "MissRecord",
    "NodeDiff",
    "PropertyDiff",
    # Schemas (Patch 4)
    "ActionPayloadSchema",
    "ClaimPredicateSchema",
    "EdgeTypeSchema",
    "EntityTypeSchema",
    "EvidencePayloadSchema",
    "FieldSchema",
    "PolicyConditionSchema",
    "SchemaIdResponse",
    "SchemaStatus",
    "SchemaValidationErrorResponse",
    "ValidationResponse",
    "ValueType",
    "ValueTypeOf",
    # Replication read-only (Patch 4)
    "LastPromotionInfo",
    "ReplicationLag",
    "ReplicationLagResponse",
    "ReplicationMode",
    "ReplicationOffset",
    "ReplicationPeer",
    "ReplicationPeerStatus",
    "ReplicationPromotionStatusResponse",
    "ReplicationRole",
    "ReplicationRoleGetResponse",
    "ReplicationStatusResponse",
    # Tagged-union helpers
    "ActionTarget",
    "ClaimObject",
    "ClaimSubject",
    "EvidenceSource",
    # Type aliases
    "ActionId",
    "ActorId",
    "ApprovalId",
    "CascadeId",
    "ClaimId",
    "CommitId",
    "EdgeId",
    "EventId",
    "EvidenceId",
    "NodeId",
    "OutcomeId",
    "PolicyDecisionId",
    "PolicyId",
    "ReplicaId",
    "SchemaId",
    "SnapshotId",
    "SubscriptionId",
    "TenantId",
    "TypeId",
    # Literal enums
    "ActionStatus",
    "ClaimKind",
    "ClaimStatus",
    "Confidence",
    "DriftDirection",
    "OutcomeKind",
    "RuntimeRole",
    "SubscriptionOutcome",
    # Errors
    "HydraAuthError",
    "HydraConnectionError",
    "HydraError",
    "HydraNotFoundError",
    "HydraRateLimitedError",
    "HydraReadOnlyFollowerError",
    "HydraServerError",
    "HydraValidationError",
]
